title = "PG2"
description = "first try\n"

[dataset]
name = "market"

[train]
batch_size = 16
num_epoch = 1

[log]
loss_freq = 50
check_freq = 1000

[train.data]
replacement = false
flip_rate = 0.5

[train.generator2]
lr = 2e-5
beta1 = 0.5
beta2 = 0.999

[train.discriminator]
lr = 2e-5
beta1 = 0.5
beta2 = 0.999

[log.model_checkpoint]
n_saved = 15
save_interval = 1000

[log.verify]
batch_size = 4
shuffle = true

[loss.mask_l1]
weight = 10
mask_ratio = 1

[loss.gan]
weight = 1

#수정1. 하이퍼파라미터 수정
[model.generator1]
num_repeat = 5
middle_features_dim = 64
channels_base = 128
image_size = [ 128, 64,]
pretrained_path = "/model/pg2/checkpoints/PG2-1/G1.pth"

#수정2. 하이퍼파라미터 수정
[model.generator2]
weight_init_way = "xavier"
num_skip_out_connect = 1
num_repeat = 3
channels_base = 128
pretrained_path = "/model/pg2/checkpoints/PG2-2/G2.pth"

[model.discriminator]
weight_init_way = "tflib"

#수정3. 경로 수정
[dataset.path.train]
image = "/content/drive/MyDrive/sangwoo/budui/Human-Pose-Transfer/data/Market-1501-v15.09.15/bounding_box_train"
bone = "/content/drive/MyDrive/kang/PG2/Human-Pose-Transfer-master/data/market/train/pose_map_image/"
mask = "/content/drive/MyDrive/kang/PG2/Human-Pose-Transfer-master/data/market/train/pose_mask_image/"
pair = "/content/drive/MyDrive/kang/PG2/Human-Pose-Transfer-master/data/market/pairs-train.csv"
annotation = "/content/drive/MyDrive/kang/PG2/Human-Pose-Transfer-master/data/market/annotation-train.csv"

[dataset.path.test]
image = "/model/generation/44/"
bone = "/model/generation/44/pose_map_image/"
mask = "/model/generation/44/pose_mask_image/"
pair = "/model/generation/44/pairs.csv"
annotation = "/model/generation/44/annotation.csv"
